name: integration
run-name: Workflow de integracao CI
on: [push]
jobs:
    integration:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v4
           with:
                fetch-depth: 0

         - uses: SonarSource/sonarqube-scan-action@v5
           env:
            SONA_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONA_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            with:
            args: >
                -Dsonar.projectKey=aula-devops
                -Dsonar.projectName=aula-devops
                -Dsonar.projectVersion=1.0.0
                -Dsonar.sources=.  